numprocs=64

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from ../data/v200_batch2/v200_batch2_0_cfg.json
Loading file ../data/v200_batch2/v200_batch2_0_cfg.json ... 

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from ../data/v200_batch2/v200_batch2_0_cfg.json
Loading file ../data/v200_batch2/v200_batch2_0_cfg.json ... 

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from ../data/v200_batch2/v200_batch2_0_cfg.json
Loading file ../data/v200_batch2/v200_batch2_0_cfg.json ... 

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from ../data/v200_batch2/v200_batch2_0_cfg.json
Loading file ../data/v200_batch2/v200_batch2_0_cfg.json ... 

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from ../data/v200_batch2/v200_batch2_0_cfg.json
Loading file ../data/v200_batch2/v200_batch2_0_cfg.json ... 

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from ../data/v200_batch2/v200_batch2_0_cfg.json
Loading file ../data/v200_batch2/v200_batch2_0_cfg.json ... 

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from ../data/v200_batch2/v200_batch2_0_cfg.json
Loading file ../data/v200_batch2/v200_batch2_0_cfg.json ... 

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from ../data/v200_batch2/v200_batch2_0_cfg.json
Loading file ../data/v200_batch2/v200_batch2_0_cfg.json ... 

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from ../data/v200_batch2/v200_batch2_0_cfg.json
Loading file ../data/v200_batch2/v200_batch2_0_cfg.json ... 

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from ../data/v200_batch2/v200_batch2_0_cfg.json
Loading file ../data/v200_batch2/v200_batch2_0_cfg.json ... 

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from ../data/v200_batch2/v200_batch2_0_cfg.json
Loading file ../data/v200_batch2/v200_batch2_0_cfg.json ... 

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from ../data/v200_batch2/v200_batch2_0_cfg.json
Loading file ../data/v200_batch2/v200_batch2_0_cfg.json ... 

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from ../data/v200_batch2/v200_batch2_0_cfg.json
Loading file ../data/v200_batch2/v200_batch2_0_cfg.json ... 

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from ../data/v200_batch2/v200_batch2_0_cfg.json
Loading file ../data/v200_batch2/v200_batch2_0_cfg.json ... 

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from ../data/v200_batch2/v200_batch2_0_cfg.json
Loading file ../data/v200_batch2/v200_batch2_0_cfg.json ... 

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from ../data/v200_batch2/v200_batch2_0_cfg.json
Loading file ../data/v200_batch2/v200_batch2_0_cfg.json ... 

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from ../data/v200_batch2/v200_batch2_0_cfg.json
Loading file ../data/v200_batch2/v200_batch2_0_cfg.json ... 

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from ../data/v200_batch2/v200_batch2_0_cfg.json
Loading file ../data/v200_batch2/v200_batch2_0_cfg.json ... 

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from ../data/v200_batch2/v200_batch2_0_cfg.json
Loading file ../data/v200_batch2/v200_batch2_0_cfg.json ... 

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from ../data/v200_batch2/v200_batch2_0_cfg.json
Loading file ../data/v200_batch2/v200_batch2_0_cfg.json ... 

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from ../data/v200_batch2/v200_batch2_0_cfg.json
Loading file ../data/v200_batch2/v200_batch2_0_cfg.json ... 

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from ../data/v200_batch2/v200_batch2_0_cfg.json
Loading file ../data/v200_batch2/v200_batch2_0_cfg.json ... 

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from ../data/v200_batch2/v200_batch2_0_cfg.json
Loading file ../data/v200_batch2/v200_batch2_0_cfg.json ... 

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from ../data/v200_batch2/v200_batch2_0_cfg.json
Loading file ../data/v200_batch2/v200_batch2_0_cfg.json ... 

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from ../data/v200_batch2/v200_batch2_0_cfg.json
Loading file ../data/v200_batch2/v200_batch2_0_cfg.json ... 

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from ../data/v200_batch2/v200_batch2_0_cfg.json
Loading file ../data/v200_batch2/v200_batch2_0_cfg.json ... 

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from ../data/v200_batch2/v200_batch2_0_cfg.json
Loading file ../data/v200_batch2/v200_batch2_0_cfg.json ... 

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from ../data/v200_batch2/v200_batch2_0_cfg.json
Loading file ../data/v200_batch2/v200_batch2_0_cfg.json ... 

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from ../data/v200_batch2/v200_batch2_0_cfg.json
Loading file ../data/v200_batch2/v200_batch2_0_cfg.json ... 

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from ../data/v200_batch2/v200_batch2_0_cfg.json
Loading file ../data/v200_batch2/v200_batch2_0_cfg.json ... 

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from ../data/v200_batch2/v200_batch2_0_cfg.json
Loading file ../data/v200_batch2/v200_batch2_0_cfg.json ... 

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from ../data/v200_batch2/v200_batch2_0_cfg.json
Loading file ../data/v200_batch2/v200_batch2_0_cfg.json ... 

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from ../data/v200_batch2/v200_batch2_0_cfg.json
Loading file ../data/v200_batch2/v200_batch2_0_cfg.json ... 

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from ../data/v200_batch2/v200_batch2_0_cfg.json
Loading file ../data/v200_batch2/v200_batch2_0_cfg.json ... 

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from ../data/v200_batch2/v200_batch2_0_cfg.json
Loading file ../data/v200_batch2/v200_batch2_0_cfg.json ... 

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from ../data/v200_batch2/v200_batch2_0_cfg.json
Loading file ../data/v200_batch2/v200_batch2_0_cfg.json ... 

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from ../data/v200_batch2/v200_batch2_0_cfg.json
Loading file ../data/v200_batch2/v200_batch2_0_cfg.json ... 

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from ../data/v200_batch2/v200_batch2_0_cfg.json
Loading file ../data/v200_batch2/v200_batch2_0_cfg.json ... 

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from ../data/v200_batch2/v200_batch2_0_cfg.json
Loading file ../data/v200_batch2/v200_batch2_0_cfg.json ... 

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from ../data/v200_batch2/v200_batch2_0_cfg.json
Loading file ../data/v200_batch2/v200_batch2_0_cfg.json ... 

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from ../data/v200_batch2/v200_batch2_0_cfg.json
Loading file ../data/v200_batch2/v200_batch2_0_cfg.json ... 

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from ../data/v200_batch2/v200_batch2_0_cfg.json
Loading file ../data/v200_batch2/v200_batch2_0_cfg.json ... 

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from ../data/v200_batch2/v200_batch2_0_cfg.json
Loading file ../data/v200_batch2/v200_batch2_0_cfg.json ... 

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from ../data/v200_batch2/v200_batch2_0_cfg.json
Loading file ../data/v200_batch2/v200_batch2_0_cfg.json ... 

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from ../data/v200_batch2/v200_batch2_0_cfg.json
Loading file ../data/v200_batch2/v200_batch2_0_cfg.json ... 

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from ../data/v200_batch2/v200_batch2_0_cfg.json
Loading file ../data/v200_batch2/v200_batch2_0_cfg.json ... 

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from ../data/v200_batch2/v200_batch2_0_cfg.json
Loading file ../data/v200_batch2/v200_batch2_0_cfg.json ... 

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from ../data/v200_batch2/v200_batch2_0_cfg.json
Loading file ../data/v200_batch2/v200_batch2_0_cfg.json ... 

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from ../data/v200_batch2/v200_batch2_0_cfg.json
Loading file ../data/v200_batch2/v200_batch2_0_cfg.json ... 

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from ../data/v200_batch2/v200_batch2_0_cfg.json
Loading file ../data/v200_batch2/v200_batch2_0_cfg.json ... 

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from ../data/v200_batch2/v200_batch2_0_cfg.json
Loading file ../data/v200_batch2/v200_batch2_0_cfg.json ... 

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from ../data/v200_batch2/v200_batch2_0_cfg.json
Loading file ../data/v200_batch2/v200_batch2_0_cfg.json ... 

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from ../data/v200_batch2/v200_batch2_0_cfg.json
Loading file ../data/v200_batch2/v200_batch2_0_cfg.json ... 

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from ../data/v200_batch2/v200_batch2_0_cfg.json
Loading file ../data/v200_batch2/v200_batch2_0_cfg.json ... 

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from ../data/v200_batch2/v200_batch2_0_cfg.json
Loading file ../data/v200_batch2/v200_batch2_0_cfg.json ... 

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from ../data/v200_batch2/v200_batch2_0_cfg.json
Loading file ../data/v200_batch2/v200_batch2_0_cfg.json ... 

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from ../data/v200_batch2/v200_batch2_0_cfg.json
Loading file ../data/v200_batch2/v200_batch2_0_cfg.json ... 

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from ../data/v200_batch2/v200_batch2_0_cfg.json
Loading file ../data/v200_batch2/v200_batch2_0_cfg.json ... 
Importing simConfig from ../data/v200_batch2/v200_batch2_0_cfg.json
Loading file ../data/v200_batch2/v200_batch2_0_cfg.json ... 

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from ../data/v200_batch2/v200_batch2_0_cfg.json
Loading file ../data/v200_batch2/v200_batch2_0_cfg.json ... 

Importing simConfig from ../data/v200_batch2/v200_batch2_0_cfg.json
Loading file ../data/v200_batch2/v200_batch2_0_cfg.json ... 

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from ../data/v200_batch2/v200_batch2_0_cfg.json
Loading file ../data/v200_batch2/v200_batch2_0_cfg.json ... 

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from ../data/v200_batch2/v200_batch2_0_cfg.json
Loading file ../data/v200_batch2/v200_batch2_0_cfg.json ... 

Reading command line arguments using syntax: python file.py [simConfig=filepath] [netParams=filepath]
Importing simConfig from ../data/v200_batch2/v200_batch2_0_cfg.json
Loading file ../data/v200_batch2/v200_batch2_0_cfg.json ... 
Loading simConfig...
Loading simConfig...
Loading simConfig...
Loading simConfig...
Loading simConfig...
Loading simConfig...
Loading simConfig...
Loading simConfig...
Loading simConfig...
Loading simConfig...
Loading simConfig...
Loading simConfig...
Loading simConfig...
Loading simConfig...
Loading simConfig...
Loading simConfig...
Loading simConfig...
Loading simConfig...
Loading simConfig...
Loading simConfig...
Loading simConfig...
Loading simConfig...
Loading simConfig...
Loading simConfig...
Loading simConfig...
Loading simConfig...
Loading simConfig...
Loading simConfig...
Loading simConfig...
Loading simConfig...
Loading simConfig...
Loading simConfig...
Loading simConfig...
Loading simConfig...
Loading simConfig...
Loading simConfig...
Loading simConfig...
Loading simConfig...
Loading simConfig...
Loading simConfig...
Loading simConfig...
Loading simConfig...
Loading simConfig...
Loading simConfig...
Loading simConfig...
Loading simConfig...
Loading simConfig...
Loading simConfig...
Loading simConfig...
Loading simConfig...
Loading simConfig...
Loading simConfig...
Loading simConfig...
Loading simConfig...
Loading simConfig...
Loading simConfig...
Loading simConfig...
Loading simConfig...
Loading simConfig...
Loading simConfig...
Loading simConfig...
Loading simConfig...
Loading simConfig...
Loading simConfig...
Importing netParams from ../data/v200_batch2/v200_batch2_netParams.py
Importing netParams from ../data/v200_batch2/v200_batch2_netParams.py
Importing netParams from ../data/v200_batch2/v200_batch2_netParams.py
Importing netParams from ../data/v200_batch2/v200_batch2_netParams.py
Importing netParams from ../data/v200_batch2/v200_batch2_netParams.py
Importing netParams from ../data/v200_batch2/v200_batch2_netParams.py
Importing netParams from ../data/v200_batch2/v200_batch2_netParams.py
Importing netParams from ../data/v200_batch2/v200_batch2_netParams.py
Importing netParams from ../data/v200_batch2/v200_batch2_netParams.py
Importing netParams from ../data/v200_batch2/v200_batch2_netParams.py
Importing netParams from ../data/v200_batch2/v200_batch2_netParams.py
Importing netParams from ../data/v200_batch2/v200_batch2_netParams.py
Importing netParams from ../data/v200_batch2/v200_batch2_netParams.py
Importing netParams from ../data/v200_batch2/v200_batch2_netParams.py
Importing netParams from ../data/v200_batch2/v200_batch2_netParams.py
Importing netParams from ../data/v200_batch2/v200_batch2_netParams.py
Importing netParams from ../data/v200_batch2/v200_batch2_netParams.py
Importing netParams from ../data/v200_batch2/v200_batch2_netParams.py
Importing netParams from ../data/v200_batch2/v200_batch2_netParams.py
Importing netParams from ../data/v200_batch2/v200_batch2_netParams.py
Importing netParams from ../data/v200_batch2/v200_batch2_netParams.py
Importing netParams from ../data/v200_batch2/v200_batch2_netParams.py
Importing netParams from ../data/v200_batch2/v200_batch2_netParams.py
Importing netParams from ../data/v200_batch2/v200_batch2_netParams.py
Importing netParams from ../data/v200_batch2/v200_batch2_netParams.py
Importing netParams from ../data/v200_batch2/v200_batch2_netParams.py
Importing netParams from ../data/v200_batch2/v200_batch2_netParams.py
Importing netParams from ../data/v200_batch2/v200_batch2_netParams.py
Importing netParams from ../data/v200_batch2/v200_batch2_netParams.py
Importing netParams from ../data/v200_batch2/v200_batch2_netParams.py
Importing netParams from ../data/v200_batch2/v200_batch2_netParams.py
Importing netParams from ../data/v200_batch2/v200_batch2_netParams.py
Importing netParams from ../data/v200_batch2/v200_batch2_netParams.py
Importing netParams from ../data/v200_batch2/v200_batch2_netParams.py
Importing netParams from ../data/v200_batch2/v200_batch2_netParams.py
Importing netParams from ../data/v200_batch2/v200_batch2_netParams.py
Importing netParams from ../data/v200_batch2/v200_batch2_netParams.py
Importing netParams from ../data/v200_batch2/v200_batch2_netParams.py
Importing netParams from ../data/v200_batch2/v200_batch2_netParams.py
Importing netParams from ../data/v200_batch2/v200_batch2_netParams.py
Importing netParams from ../data/v200_batch2/v200_batch2_netParams.py
Importing netParams from ../data/v200_batch2/v200_batch2_netParams.py
Importing netParams from ../data/v200_batch2/v200_batch2_netParams.py
Importing netParams from ../data/v200_batch2/v200_batch2_netParams.py
Importing netParams from ../data/v200_batch2/v200_batch2_netParams.py
Importing netParams from ../data/v200_batch2/v200_batch2_netParams.py
Importing netParams from ../data/v200_batch2/v200_batch2_netParams.py
Importing netParams from ../data/v200_batch2/v200_batch2_netParams.py
Importing netParams from ../data/v200_batch2/v200_batch2_netParams.py
Importing netParams from ../data/v200_batch2/v200_batch2_netParams.py
Importing netParams from ../data/v200_batch2/v200_batch2_netParams.py
Importing netParams from ../data/v200_batch2/v200_batch2_netParams.py
Importing netParams from ../data/v200_batch2/v200_batch2_netParams.py
Importing netParams from ../data/v200_batch2/v200_batch2_netParams.py
Importing netParams from ../data/v200_batch2/v200_batch2_netParams.py
Importing netParams from ../data/v200_batch2/v200_batch2_netParams.py
Importing netParams from ../data/v200_batch2/v200_batch2_netParams.py
Importing netParams from ../data/v200_batch2/v200_batch2_netParams.py
Importing netParams from ../data/v200_batch2/v200_batch2_netParams.py
Importing netParams from ../data/v200_batch2/v200_batch2_netParams.py
Importing netParams from ../data/v200_batch2/v200_batch2_netParams.py
Importing netParams from ../data/v200_batch2/v200_batch2_netParams.py
Importing netParams from ../data/v200_batch2/v200_batch2_netParams.py
Importing netParams from ../data/v200_batch2/v200_batch2_netParams.py

Start time:  2023-08-15 13:28:54.017844

Creating network of 245 cell populations on 64 hosts...
  Number of cells on node 14: 604 
  Number of cells on node 43: 603 
  Number of cells on node 61: 603 
  Number of cells on node 36: 603 
  Number of cells on node 2: 604 
  Number of cells on node 47: 603 
  Number of cells on node 57: 603 
  Number of cells on node 6: 604 
  Number of cells on node 52: 603 
  Number of cells on node 59: 603 
  Number of cells on node 49: 603 
  Number of cells on node 10: 604 
  Number of cells on node 56: 603 
  Number of cells on node 35: 603 
  Number of cells on node 53: 603 
  Number of cells on node 38: 603 
  Number of cells on node 28: 603 
  Number of cells on node 39: 603 
  Number of cells on node 13: 604 
  Number of cells on node 46: 603 
  Number of cells on node 24: 603 
  Number of cells on node 51: 603 
  Number of cells on node 1: 604 
  Number of cells on node 20: 603 
  Number of cells on node 42: 603 
  Number of cells on node 55: 603 
  Number of cells on node 16: 604 
  Number of cells on node 34: 603 
  Number of cells on node 63: 603 
  Number of cells on node 26: 603 
  Number of cells on node 60: 603 
  Number of cells on node 3: 604 
  Number of cells on node 5: 604 
  Number of cells on node 22: 603 
  Number of cells on node 48: 603 
  Number of cells on node 11: 604 
  Number of cells on node 40: 603 
  Number of cells on node 45: 603 
  Number of cells on node 18: 604 
  Number of cells on node 9: 604 
  Number of cells on node 15: 604 
  Number of cells on node 44: 603 
  Number of cells on node 33: 603 
  Number of cells on node 30: 603 
  Number of cells on node 7: 604 
  Number of cells on node 41: 603 
  Number of cells on node 32: 603 
  Number of cells on node 37: 603 
  Number of cells on node 62: 603 
  Number of cells on node 27: 603 
  Number of cells on node 8: 604 
  Number of cells on node 25: 603 
  Number of cells on node 21: 603 
  Number of cells on node 50: 603 
  Number of cells on node 31: 603 
  Number of cells on node 12: 604 
  Number of cells on node 29: 603 
  Number of cells on node 17: 604 
  Number of cells on node 54: 603 
  Number of cells on node 19: 604 
  Number of cells on node 0: 604 
  Number of cells on node 58: 603 
  Number of cells on node 23: 603 
  Number of cells on node 4: 604 
  Done; cell creation time = 0.83 s.
Making connections...
  Number of connections on node 21: 0 
  Number of connections on node 2: 0 
  Number of connections on node 5: 136 
  Number of synaptic contacts on node 5: 1073 
  Number of connections on node 13: 0 
  Number of connections on node 7: 217 
  Number of synaptic contacts on node 7: 1248 
  Number of connections on node 54: 9 
  Number of synaptic contacts on node 54: 74 
  Number of connections on node 39: 0 
  Number of connections on node 17: 342 
  Number of synaptic contacts on node 17: 1402 
  Number of connections on node 4: 0 
  Number of connections on node 26: 668 
  Number of synaptic contacts on node 26: 2719 
  Number of connections on node 6: 305 
  Number of synaptic contacts on node 6: 1342 
  Number of connections on node 23: 0 
  Number of connections on node 55: 75 
  Number of synaptic contacts on node 55: 550 
  Number of connections on node 30: 797 
  Number of synaptic contacts on node 30: 4466 
  Number of connections on node 9: 452 
  Number of synaptic contacts on node 9: 1699 
  Number of connections on node 42: 0 
  Number of connections on node 20: 0 
  Number of connections on node 38: 884 
  Number of synaptic contacts on node 38: 3771 
  Number of connections on node 24: 377 
  Number of synaptic contacts on node 24: 1565 
  Number of connections on node 28: 506 
  Number of synaptic contacts on node 28: 2119 
  Number of connections on node 27: 816 
  Number of synaptic contacts on node 27: 3585 
  Number of connections on node 63: 734 
  Number of synaptic contacts on node 63: 4309 
  Number of connections on node 43: 635 
  Number of synaptic contacts on node 43: 3114 
  Number of connections on node 56: 389 
  Number of synaptic contacts on node 56: 2508 
  Number of connections on node 36: 443 
  Number of synaptic contacts on node 36: 1834 
  Number of connections on node 32: 500 
  Number of synaptic contacts on node 32: 2070 
  Number of connections on node 47: 0 
  Number of connections on node 51: 0 
  Number of connections on node 57: 0 
  Number of connections on node 53: 232 
  Number of synaptic contacts on node 53: 1397 
  Number of connections on node 1: 0 
  Number of connections on node 50: 104 
  Number of synaptic contacts on node 50: 559 
  Number of connections on node 22: 0 
  Number of connections on node 34: 467 
  Number of synaptic contacts on node 34: 1882 
  Number of connections on node 46: 514 
  Number of synaptic contacts on node 46: 2058 
  Number of connections on node 58: 0 
  Number of connections on node 25: 721 
  Number of synaptic contacts on node 25: 2833 
  Number of connections on node 41: 0 
  Number of connections on node 16: 342 
  Number of synaptic contacts on node 16: 1391 
  Number of connections on node 52: 203 
  Number of synaptic contacts on node 52: 1692 
  Number of connections on node 49: 0 
  Number of connections on node 15: 659 
  Number of synaptic contacts on node 15: 2926 
  Number of connections on node 59: 0 
  Number of connections on node 3: 348 
  Number of synaptic contacts on node 3: 2653 
  Number of connections on node 0: 0 
  Number of connections on node 62: 669 
  Number of synaptic contacts on node 62: 3835 
  Number of connections on node 18: 499 
  Number of synaptic contacts on node 18: 2729 
  Number of connections on node 45: 499 
  Number of synaptic contacts on node 45: 1947 
  Number of connections on node 31: 1060 
  Number of synaptic contacts on node 31: 5245 
  Number of connections on node 61: 693 
  Number of synaptic contacts on node 61: 3925 
  Number of connections on node 14: 649 
  Number of synaptic contacts on node 14: 3296 
  Number of connections on node 10: 463 
  Number of synaptic contacts on node 10: 1782 
  Number of connections on node 19: 361 
  Number of synaptic contacts on node 19: 1466 
  Number of connections on node 44: 540 
  Number of synaptic contacts on node 44: 2013 
  Number of connections on node 48: 0 
  Number of connections on node 29: 628 
  Number of synaptic contacts on node 29: 3051 
  Number of connections on node 35: 480 
  Number of synaptic contacts on node 35: 2078 
  Number of connections on node 11: 856 
  Number of synaptic contacts on node 11: 3408 
  Number of connections on node 37: 490 
  Number of synaptic contacts on node 37: 2046 
  Number of connections on node 33: 474 
  Number of synaptic contacts on node 33: 1971 
  Number of connections on node 40: 0 
  Number of connections on node 12: 902 
  Number of synaptic contacts on node 12: 3530 
  Number of connections on node 60: 672 
  Number of synaptic contacts on node 60: 3851 
  Number of connections on node 8: 468 
  Number of synaptic contacts on node 8: 1803 
  Done; cell connection time = 66.93 s.
Adding stims...
  Number of stims on node 59: 0 
  Number of stims on node 1: 0 
  Number of stims on node 49: 0 
  Number of stims on node 39: 0 
  Number of stims on node 5: 10 
  Number of stims on node 48: 0 
  Number of stims on node 58: 0 
  Number of stims on node 29: 30 
  Number of stims on node 7: 10 
  Number of stims on node 61: 10 
  Number of stims on node 3: 20 
  Number of stims on node 45: 10 
  Number of stims on node 27: 30 
  Number of stims on node 31: 30 
  Number of stims on node 23: 0 
  Number of stims on node 13: 0 
  Number of stims on node 51: 0 
  Number of stims on node 10: 10 
  Number of stims on node 60: 10 
  Number of stims on node 30: 40 
  Number of stims on node 25: 20 
  Number of stims on node 54: 10 
  Number of stims on node 57: 0 
  Number of stims on node 40: 0 
  Number of stims on node 43: 20 
  Number of stims on node 11: 20 
  Number of stims on node 21: 0 
  Number of stims on node 63: 30 
  Number of stims on node 19: 20 
  Number of stims on node 46: 10 
  Number of stims on node 36: 20 
  Number of stims on node 9: 10 
  Number of stims on node 24: 10 
  Number of stims on node 18: 30 
  Number of stims on node 35: 20 
  Number of stims on node 17: 10 
  Number of stims on node 41: 0 
  Number of stims on node 2: 0 
  Number of stims on node 20: 0 
  Number of stims on node 53: 20 
  Number of stims on node 47: 0 
  Number of stims on node 33: 20 
  Number of stims on node 6: 10 
  Number of stims on node 12: 20 
  Number of stims on node 4: 0 
  Number of stims on node 42: 0 
  Number of stims on node 28: 20 
  Number of stims on node 56: 20 
  Number of stims on node 22: 0 
  Number of stims on node 44: 10 
  Number of stims on node 26: 20 
  Number of stims on node 0: 0 
  Number of stims on node 16: 10 
  Number of stims on node 34: 20 
  Number of stims on node 62: 10 
  Number of stims on node 52: 10 
  Number of stims on node 14: 20 
  Number of stims on node 32: 20 
  Number of stims on node 15: 10 
  Number of stims on node 38: 30 
  Number of stims on node 55: 20 
  Number of stims on node 50: 10 
  Number of stims on node 37: 20 
  Number of stims on node 8: 10 
  Done; cell stims creation time = 6.61 s.
Recording 0 traces of 0 types on node 21
Recording 0 traces of 0 types on node 39
Recording 0 traces of 0 types on node 13
Recording 1 traces of 1 types on node 54
Recording 0 traces of 0 types on node 20
Recording 0 traces of 0 types on node 23
Recording 0 traces of 0 types on node 4
Recording 0 traces of 0 types on node 42
Recording 2 traces of 1 types on node 55
Recording 1 traces of 1 types on node 5
Recording 0 traces of 0 types on node 2
Recording 1 traces of 1 types on node 9
Recording 1 traces of 1 types on node 26
Recording 2 traces of 1 types on node 56
Recording 1 traces of 1 types on node 8
Recording 1 traces of 1 types on node 6
Recording 0 traces of 0 types on node 32
Recording 0 traces of 0 types on node 49
Recording 2 traces of 1 types on node 43
Recording 0 traces of 0 types on node 57
Recording 3 traces of 1 types on node 63
Recording 3 traces of 1 types on node 30
Recording 1 traces of 1 types on node 17
Recording 1 traces of 1 types on node 38
Recording 1 traces of 1 types on node 7
Recording 0 traces of 0 types on node 22
Recording 0 traces of 0 types on node 0
Recording 2 traces of 1 types on node 27
Recording 1 traces of 1 types on node 24
Recording 0 traces of 0 types on node 36
Recording 0 traces of 0 types on node 51
Recording 0 traces of 0 types on node 59
Recording 0 traces of 0 types on node 1
Recording 1 traces of 1 types on node 28
Recording 0 traces of 0 types on node 47
Recording 0 traces of 0 types on node 41
Recording 0 traces of 0 types on node 58
Recording 1 traces of 1 types on node 52
Recording 1 traces of 1 types on node 10
Recording 2 traces of 1 types on node 37
Recording 1 traces of 1 types on node 16
Recording 0 traces of 0 types on node 40
Recording 0 traces of 0 types on node 48
Recording 2 traces of 1 types on node 14
Recording 2 traces of 1 types on node 25
Recording 1 traces of 1 types on node 29
Recording 1 traces of 1 types on node 61
Recording 2 traces of 1 types on node 3
Recording 1 traces of 1 types on node 15
Recording 1 traces of 1 types on node 62
Recording 1 traces of 1 types on node 46
Recording 1 traces of 1 types on node 44
Recording 2 traces of 1 types on node 12
Recording 1 traces of 1 types on node 35
Recording 2 traces of 1 types on node 19
Recording 1 traces of 1 types on node 60
Recording 3 traces of 1 types on node 18
Recording 1 traces of 1 types on node 50
Recording 2 traces of 1 types on node 11
Recording 2 traces of 1 types on node 53
Recording 1 traces of 1 types on node 45
Recording 2 traces of 1 types on node 31
Recording 1 traces of 1 types on node 33
Recording 1 traces of 1 types on node 34
0.0s

Running simulation using NEURON for 2000.0 ms...
0.1s
0.2s
0.3s
0.4s
0.5s
0.6s
0.7s
0.8s
0.9s
1.0s
1.1s
1.2s
1.3s
1.4s
1.5s
1.6s
1.7s
1.8s
1.9s
2.0s
  Done; run time = 46.71 s; real-time ratio: 0.04.

Gathering data...
  Done; gather time = 3.95 s.

Analyzing...
  Cells: 38612
  Connections: 0 (0.00 per cell)
  Spikes: 236217 (3.06 Hz)
  Simulated time: 2.0 s; 64 workers
  Run time: 46.71 s
   presyn_L1_DAC_bNA : 0.000 Hz
   L1_DAC_cNA : 0.000 Hz
   presyn_L1_DAC_cNA : 0.000 Hz
   presyn_L1_DLAC_cNA : 0.000 Hz
   L1_HAC_bNA : 0.000 Hz
   presyn_L1_HAC_bNA : 0.000 Hz
   presyn_L1_HAC_cIR : 0.000 Hz
   presyn_L1_HAC_cNA : 0.000 Hz
   presyn_L1_NGC-DA_bNA : 0.000 Hz
   presyn_L1_NGC-DA_cAC : 0.000 Hz
   presyn_L1_NGC-DA_cNA : 0.010 Hz
   presyn_L1_NGC-DA_cST : 0.000 Hz
   L1_NGC-SA_cNA : 0.000 Hz
   presyn_L1_NGC-SA_cNA : 0.010 Hz
   presyn_L1_SLAC_bNA : 0.036 Hz
   presyn_L1_SLAC_cAC : 0.000 Hz
   L1_SLAC_cNA : 0.000 Hz
   presyn_L1_SLAC_cNA : 0.000 Hz
   presyn_L23_BP_bAC : 1.000 Hz
   presyn_L23_BP_bIR : 0.250 Hz
   presyn_L23_BP_bNA : 3.500 Hz
   presyn_L23_BP_cAC : 3.357 Hz
   presyn_L23_BP_cNA : 5.375 Hz
   presyn_L23_BP_dST : 1.167 Hz
   presyn_L23_BTC_bAC : 0.000 Hz
   presyn_L23_BTC_bIR : 0.000 Hz
   presyn_L23_BTC_bNA : 0.000 Hz
   presyn_L23_BTC_cAC : 0.024 Hz
   presyn_L23_BTC_cNA : 0.000 Hz
   presyn_L23_ChC_cAC : 0.261 Hz
   presyn_L23_ChC_cNA : 0.261 Hz
   presyn_L23_ChC_dNA : 0.133 Hz
   presyn_L23_DBC_bAC : 0.500 Hz
   presyn_L23_DBC_bIR : 0.016 Hz
   L23_DBC_bNA : 0.000 Hz
   presyn_L23_DBC_bNA : 0.370 Hz
   presyn_L23_DBC_cAC : 0.500 Hz
   presyn_L23_LBC_bAC : 0.229 Hz
   presyn_L23_LBC_bNA : 3.148 Hz
   presyn_L23_LBC_cAC : 1.236 Hz
   presyn_L23_LBC_cNA : 2.066 Hz
   presyn_L23_LBC_cST : 0.909 Hz
   L23_LBC_dNA : 0.000 Hz
   presyn_L23_LBC_dNA : 2.171 Hz
   presyn_L23_MC_bAC : 0.000 Hz
   presyn_L23_MC_bNA : 0.000 Hz
   presyn_L23_MC_cAC : 0.000 Hz
   presyn_L23_MC_cNA : 0.000 Hz
   presyn_L23_MC_dNA : 0.000 Hz
   presyn_L23_NBC_bAC : 0.179 Hz
   presyn_L23_NBC_bNA : 0.667 Hz
   presyn_L23_NBC_cAC : 0.200 Hz
   presyn_L23_NBC_cIR : 0.000 Hz
   L23_NBC_cNA : 0.000 Hz
   presyn_L23_NBC_cNA : 0.177 Hz
   presyn_L23_NBC_dNA : 0.015 Hz
   presyn_L23_NGC_bNA : 0.000 Hz
   presyn_L23_NGC_cAC : 0.000 Hz
   presyn_L23_NGC_cNA : 0.061 Hz
   presyn_L23_NGC_cST : 0.000 Hz
   L23_PC_cAD : 0.292 Hz
   presyn_L23_PC_cAD : 0.255 Hz
   presyn_L23_SBC_bNA : 3.392 Hz
   presyn_L23_SBC_cAC : 2.233 Hz
   presyn_L23_SBC_dNA : 1.772 Hz
   presyn_L4_BP_bAC : 8.500 Hz
   presyn_L4_BP_bIR : 6.000 Hz
   presyn_L4_BP_bNA : 5.000 Hz
   presyn_L4_BP_cAC : 3.000 Hz
   presyn_L4_BP_cNA : 15.500 Hz
   presyn_L4_BP_dST : 0.000 Hz
   presyn_L4_BTC_bAC : 1.000 Hz
   presyn_L4_BTC_bIR : 0.000 Hz
   presyn_L4_BTC_bST : 0.750 Hz
   presyn_L4_BTC_cAC : 5.389 Hz
   presyn_L4_BTC_cNA : 7.500 Hz
   presyn_L4_BTC_dNA : 0.000 Hz
   presyn_L4_ChC_cAC : 16.167 Hz
   presyn_L4_ChC_cNA : 13.333 Hz
   presyn_L4_ChC_dNA : 0.000 Hz
   presyn_L4_DBC_bAC : 3.500 Hz
   presyn_L4_DBC_bIR : 0.000 Hz
   presyn_L4_DBC_bNA : 0.375 Hz
   presyn_L4_DBC_bST : 0.000 Hz
   presyn_L4_DBC_cAC : 1.500 Hz
   L4_DBC_cIR : 0.000 Hz
   presyn_L4_DBC_cIR : 0.000 Hz
   presyn_L4_DBC_cNA : 1.875 Hz
   presyn_L4_LBC_cAC : 12.545 Hz
   presyn_L4_LBC_cNA : 21.714 Hz
   presyn_L4_LBC_cST : 10.968 Hz
   L4_LBC_dNA : 17.500 Hz
   presyn_L4_LBC_dNA : 18.978 Hz
   presyn_L4_LBC_dST : 14.056 Hz
   presyn_L4_MC_bAC : 0.000 Hz
   presyn_L4_MC_bNA : 0.000 Hz
   presyn_L4_MC_cAC : 0.000 Hz
   presyn_L4_MC_cNA : 0.028 Hz
   presyn_L4_MC_dNA : 0.000 Hz
   presyn_L4_NBC_cAC : 12.650 Hz
   presyn_L4_NBC_cIR : 8.400 Hz
   presyn_L4_NBC_cNA : 26.422 Hz
   presyn_L4_NBC_dNA : 14.764 Hz
   presyn_L4_NGC_bNA : 3.500 Hz
   presyn_L4_NGC_cAC : 4.000 Hz
   presyn_L4_NGC_cNA : 3.000 Hz
   presyn_L4_NGC_cST : 0.000 Hz
   L4_PC_cAD : 0.625 Hz
   presyn_L4_PC_cAD : 1.108 Hz
   presyn_L4_SBC_bNA : 21.024 Hz
   presyn_L4_SBC_cAC : 13.000 Hz
   presyn_L4_SBC_dNA : 21.147 Hz
   L4_SP_cAD : 0.000 Hz
   presyn_L4_SP_cAD : 2.278 Hz
   L4_SS_cAD : 3.750 Hz
   presyn_L4_SS_cAD : 2.526 Hz
   presyn_L5_BP_bAC : 8.167 Hz
   presyn_L5_BP_bIR : 0.300 Hz
   presyn_L5_BP_bNA : 19.556 Hz
   presyn_L5_BP_cAC : 14.500 Hz
   presyn_L5_BP_cNA : 29.000 Hz
   presyn_L5_BP_dST : 0.000 Hz
   presyn_L5_BTC_bAC : 6.962 Hz
   presyn_L5_BTC_cAC : 9.190 Hz
   presyn_L5_BTC_cNA : 11.846 Hz
   presyn_L5_ChC_cAC : 22.500 Hz
   presyn_L5_ChC_cNA : 30.286 Hz
   presyn_L5_ChC_dNA : 28.500 Hz
   presyn_L5_DBC_bAC : 2.944 Hz
   presyn_L5_DBC_bIR : 0.029 Hz
   presyn_L5_DBC_bNA : 4.722 Hz
   presyn_L5_DBC_bST : 0.000 Hz
   presyn_L5_DBC_cAC : 7.556 Hz
   presyn_L5_DBC_cIR : 0.029 Hz
   presyn_L5_DBC_cNA : 10.833 Hz
   presyn_L5_LBC_bAC : 9.000 Hz
   presyn_L5_LBC_cAC : 17.400 Hz
   presyn_L5_LBC_cIR : 3.692 Hz
   presyn_L5_LBC_cNA : 38.730 Hz
   L5_LBC_cST : 65.000 Hz
   presyn_L5_LBC_cST : 25.361 Hz
   L5_LBC_dNA : 117.000 Hz
   presyn_L5_LBC_dNA : 29.972 Hz
   presyn_L5_LBC_dST : 20.673 Hz
   presyn_L5_MC_bAC : 0.386 Hz
   presyn_L5_MC_bIR : 0.000 Hz
   presyn_L5_MC_bST : 0.000 Hz
   presyn_L5_MC_cAC : 0.746 Hz
   L5_MC_cNA : 1.500 Hz
   presyn_L5_MC_cNA : 0.133 Hz
   presyn_L5_MC_cST : 0.000 Hz
   presyn_L5_MC_dNA : 0.000 Hz
   presyn_L5_NBC_bAC : 7.250 Hz
   presyn_L5_NBC_bIR : 2.643 Hz
   presyn_L5_NBC_bST : 16.593 Hz
   presyn_L5_NBC_cAC : 22.050 Hz
   presyn_L5_NBC_cIR : 10.286 Hz
   presyn_L5_NBC_cNA : 33.333 Hz
   L5_NBC_cST : 1.500 Hz
   presyn_L5_NBC_cST : 19.064 Hz
   presyn_L5_NBC_dST : 24.462 Hz
   presyn_L5_NGC_bNA : 12.500 Hz
   presyn_L5_NGC_cAC : 14.500 Hz
   presyn_L5_NGC_cNA : 28.500 Hz
   presyn_L5_NGC_cST : 0.500 Hz
   L5_SBC_bNA : 29.000 Hz
   presyn_L5_SBC_bNA : 20.750 Hz
   presyn_L5_SBC_cAC : 12.167 Hz
   L5_SBC_dNA : 59.500 Hz
   presyn_L5_SBC_dNA : 47.583 Hz
   L5_STPC_cAD : 0.500 Hz
   presyn_L5_STPC_cAD : 3.770 Hz
   L5_TTPC1_cAD : 4.625 Hz
   presyn_L5_TTPC1_cAD : 2.863 Hz
   L5_TTPC2_cAD : 1.500 Hz
   presyn_L5_TTPC2_cAD : 3.067 Hz
   presyn_L5_UTPC_cAD : 5.291 Hz
   L6_BPC_cAD : 1.000 Hz
   presyn_L6_BPC_cAD : 1.537 Hz
   presyn_L6_BP_bAC : 5.000 Hz
   presyn_L6_BP_bIR : 0.000 Hz
   presyn_L6_BP_bNA : 12.263 Hz
   presyn_L6_BP_cAC : 12.553 Hz
   presyn_L6_BP_cNA : 20.400 Hz
   presyn_L6_BP_dST : 0.000 Hz
   presyn_L6_BTC_bAC : 5.900 Hz
   presyn_L6_BTC_cAC : 6.868 Hz
   presyn_L6_BTC_cNA : 14.000 Hz
   presyn_L6_ChC_cAC : 8.417 Hz
   presyn_L6_ChC_cNA : 44.833 Hz
   presyn_L6_ChC_dNA : 24.250 Hz
   presyn_L6_DBC_bAC : 5.833 Hz
   presyn_L6_DBC_bIR : 0.250 Hz
   presyn_L6_DBC_bNA : 6.333 Hz
   presyn_L6_DBC_bST : 2.667 Hz
   presyn_L6_DBC_cAC : 8.833 Hz
   presyn_L6_DBC_cIR : 1.833 Hz
   presyn_L6_DBC_cNA : 2.667 Hz
   L6_IPC_cAD : 2.107 Hz
   presyn_L6_IPC_cAD : 2.289 Hz
   presyn_L6_LBC_bAC : 5.744 Hz
   presyn_L6_LBC_bIR : 2.724 Hz
   presyn_L6_LBC_bNA : 48.698 Hz
   L6_LBC_bST : 7.000 Hz
   presyn_L6_LBC_bST : 21.821 Hz
   presyn_L6_LBC_cNA : 41.595 Hz
   presyn_L6_LBC_cST : 21.291 Hz
   presyn_L6_MC_bAC : 0.000 Hz
   presyn_L6_MC_bIR : 0.000 Hz
   presyn_L6_MC_bNA : 0.000 Hz
   presyn_L6_MC_bST : 0.000 Hz
   L6_MC_cAC : 0.500 Hz
   presyn_L6_MC_cAC : 0.054 Hz
   presyn_L6_MC_cIR : 0.000 Hz
   presyn_L6_MC_cNA : 0.036 Hz
   presyn_L6_NBC_bAC : 6.929 Hz
   presyn_L6_NBC_bIR : 3.107 Hz
   presyn_L6_NBC_bST : 30.426 Hz
   L6_NBC_cAC : 12.500 Hz
   presyn_L6_NBC_cAC : 11.408 Hz
   presyn_L6_NBC_cIR : 3.821 Hz
   L6_NBC_cNA : 11.000 Hz
   presyn_L6_NBC_cNA : 29.806 Hz
   L6_NBC_cST : 34.000 Hz
   presyn_L6_NBC_cST : 23.189 Hz
   presyn_L6_NBC_dST : 28.429 Hz
   presyn_L6_NGC_bNA : 13.000 Hz
   presyn_L6_NGC_cAC : 11.750 Hz
   presyn_L6_NGC_cNA : 22.273 Hz
   presyn_L6_NGC_cST : 0.250 Hz
   presyn_L6_SBC_bNA : 37.021 Hz
   presyn_L6_SBC_cAC : 22.146 Hz
   presyn_L6_SBC_dNA : 25.868 Hz
   L6_TPC_L1_cAD : 0.000 Hz
   presyn_L6_TPC_L1_cAD : 2.030 Hz
   L6_TPC_L4_cAD : 10.500 Hz
   presyn_L6_TPC_L4_cAD : 2.808 Hz
   L6_UTPC_cAD : 1.625 Hz
   presyn_L6_UTPC_cAD : 2.957 Hz
   presyn_ss_RTN_o : 9.582 Hz
   presyn_ss_RTN_m : 10.286 Hz
   presyn_ss_RTN_i : 9.146 Hz
   presyn_VPL_sTC : 1.100 Hz
   presyn_VPM_sTC : 1.279 Hz
   presyn_POm_sTC_s1 : 1.525 Hz
Saving output as ../data/v200_batch2/v200_batch2_0_data.pkl ... 
Finished saving!
  Done; saving time = 8.82 s.
Plotting 2D representation of network cell locations and connections...
Preparing spike data...
Plotting raster...
Plotting recorded cell traces ... trace
  Done; plotting time = 11.39 s

Total time = 172.20 s


 L1_DAC_cNA   N = 39
Plotting recorded cell traces ... trace


 L1_HAC_bNA   N = 19
Plotting recorded cell traces ... trace


 L1_NGC-SA_cNA   N = 52
Plotting recorded cell traces ... trace


 L1_SLAC_cNA   N = 19
Plotting recorded cell traces ... trace


 L23_DBC_bNA   N = 70
Plotting recorded cell traces ... trace


 L23_LBC_dNA   N = 188
Plotting recorded cell traces ... trace


 L23_NBC_cNA   N = 80
Plotting recorded cell traces ... trace


 L23_PC_cAD   N = 5877
Plotting recorded cell traces ... trace


 L4_DBC_cIR   N = 7
Plotting recorded cell traces ... trace


 L4_LBC_dNA   N = 46
Plotting recorded cell traces ... trace


 L4_PC_cAD   N = 2674
Plotting recorded cell traces ... trace


 L4_SP_cAD   N = 1098
Plotting recorded cell traces ... trace


 L4_SS_cAD   N = 406
Plotting recorded cell traces ... trace


 L5_LBC_cST   N = 37
Plotting recorded cell traces ... trace


 L5_LBC_dNA   N = 37
Plotting recorded cell traces ... trace


 L5_MC_cNA   N = 16
Plotting recorded cell traces ... trace


 L5_NBC_cST   N = 40
Plotting recorded cell traces ... trace


 L5_SBC_bNA   N = 9
Plotting recorded cell traces ... trace


 L5_SBC_dNA   N = 7
Plotting recorded cell traces ... trace


 L5_STPC_cAD   N = 302
Plotting recorded cell traces ... trace


 L5_TTPC1_cAD   N = 2403
Plotting recorded cell traces ... trace


 L5_TTPC2_cAD   N = 2003
Plotting recorded cell traces ... trace


 L6_BPC_cAD   N = 3174
Plotting recorded cell traces ... trace


 L6_IPC_cAD   N = 3476
Plotting recorded cell traces ... trace


 L6_LBC_bST   N = 124
Plotting recorded cell traces ... trace


 L6_MC_cAC   N = 94
Plotting recorded cell traces ... trace


 L6_NBC_cAC   N = 39
Plotting recorded cell traces ... trace


 L6_NBC_cNA   N = 37
Plotting recorded cell traces ... trace


 L6_NBC_cST   N = 39
Plotting recorded cell traces ... trace


 L6_TPC_L1_cAD   N = 1637
Plotting recorded cell traces ... trace


 L6_TPC_L4_cAD   N = 1440
Plotting recorded cell traces ... trace


 L6_UTPC_cAD   N = 1735
Plotting recorded cell traces ... trace
